#!/bin/sh
# Bitmask Post-Instalation script
# (c) LEAP Encryption access Project
# We copy the bitmask-helper plist to the LaunchDaemons folder, and load the bitmask-helper that runs as root.

LOG=/tmp/bitmask-install.log

cp se.leap.bitmask-helper.plist /Library/LaunchDaemons/ \
	&& echo `date` ":: Bitmask post-install: copied bitmask-helper Plist." >> $LOG
launchctl load /Library/LaunchDaemons/se.leap.bitmask-helper.plist && echo `date` ":: Bitmask post-install: loaded bitmask-helper." >> $LOG
echo `date` ":: Bitmask post-install: ok." >> $LOG
exit 0
