#!/bin/sh
# Bitmask Pre-Instalation script
[[ -f /Library/LaunchDaemons/se.leap.bitmask-helper.plist ]] && launchctl unload /Library/LaunchDaemons/se.leap.bitmask-helper.plist
echo `date` "::Bitmask pre-installation script succeeded." >> /tmp/bitmask-install.log
exit 0
